<a href="https://colab.research.google.com/github/VrajeshPatel20/EECSYORKU/blob/master/training_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('1LbRGGTv6w8ORcbQVjpw1T69yQ307dDo5')

     |████████████████████████████████| 71kB 3.6MB/s 


In [2]:
!pip install jovian --upgrade --quiet

In [3]:
import numpy as np
import torch

In [4]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [5]:
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [6]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [7]:
print(inputs,targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]]) tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [8]:
w = torch.randn(2,3,requires_grad=True)
b = torch.randn(2,requires_grad=True)

print(w)
print(b)

tensor([[-0.0427,  0.2426,  0.5903],
        [-0.5732,  0.3423,  1.0997]], requires_grad=True)
tensor([0.7096, 2.4053], requires_grad=True)


In [9]:
inputs @ w.t() + b

tensor([[39.2295, 30.7815],
        [55.9515, 50.7454],
        [63.7406, 62.1850],
        [28.6271, -0.6543],
        [62.3732, 72.6922]], grad_fn=<AddBackward0>)

In [10]:
def model(x):
  return x @ w.t() + b

In [11]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [12]:
preds = model(inputs)
print(preds)

tensor([[39.2295, 30.7815],
        [55.9515, 50.7454],
        [63.7406, 62.1850],
        [28.6271, -0.6543],
        [62.3732, 72.6922]], grad_fn=<AddBackward0>)


In [13]:
diff = preds - targets
torch.sum(diff*diff)/diff.numel()

tensor(1829.7375, grad_fn=<DivBackward0>)

In [14]:
def mse(target1,target2):
  diff = target1-target2
  return torch.sum(diff*diff) / diff.numel()

In [15]:
loss = mse(preds,targets)

In [16]:
loss.backward()

In [17]:
print(w)
print(w.grad)

tensor([[-0.0427,  0.2426,  0.5903],
        [-0.5732,  0.3423,  1.0997]], requires_grad=True)
tensor([[-2087.7031, -2869.5728, -1625.5912],
        [-4126.6001, -4520.7881, -2728.9431]])


In [18]:
print(b)
print(b.grad)

tensor([0.7096, 2.4053], requires_grad=True)
tensor([-26.2156, -48.8500])


In [19]:
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5

In [20]:
loss = mse(model(inputs),targets)
print(loss)

tensor(1281.9192, grad_fn=<DivBackward0>)


In [21]:
w.grad.zero_()
b.grad.zero_()

tensor([0., 0.])

In [22]:
for i in range(100):
  preds = model(inputs)
  loss = mse(preds,targets)
  loss.backward()
  with torch.no_grad():
    w -= w.grad *1e-5
    b -= b.grad *1e-5
    w.grad.zero_()
    b.grad.zero_()

In [23]:
print(mse(model(inputs),targets))

tensor(47.8038, grad_fn=<DivBackward0>)


In [ ]:
import jovian
jovian.commit(project='02-linear-regression')

[jovian] Detected Colab notebook...
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: 

In [ ]:
import torch.nn as nn

In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [ ]:
from torch.utils.data import TensorDataset

In [ ]:
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

In [ ]:
from torch.utils.data import DataLoader

In [ ]:
model = nn.Linear(3,2)
print(model.weight)
print(model.bias)

In [ ]:
import torch.nn.functional as F

In [ ]:
loss_fn = F.mse_loss
loss = loss_fn(model(inputs),targets)
print(loss)


In [ ]:
opt = torch.optim.SGD(model.parameters(),lr = 1e-5)


In [ ]:
jovian.commit(project='02-linear-regression')

In [ ]:
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))